### ISSUE TITLE
Image no longer available?

### ISSUE THREAD

**Issue by pixiono** [kaidotdev/kube-trivy-exporter#6]
Hello,

i have tried to get the exporter to work, unfortunately I have an ImagePullBackOff error.

I tried to replay the whole thing manually: 
```
$ docker login docker.pkg.github.com
Username: pixiono
Password:

Login Succeeded

$ docker pull docker.pkg.github.com/kaidotdev/kube-trivy-exporter/kube-trivy-exporter:v0.1.2
Error response from daemon: manifest for docker.pkg.github.com/kaidotdev/kube-trivy-exporter/kube-trivy-exporter:v0.1.2 not found: manifest unknown: Docker image reference kube-trivy-exporter:v0.1.2 not found under repo "kaidotdev"
```

Has the image been removed?

**Comment by kaidotdev** [comment]
Oh, I guess I accidentally released as 1.0.2.
https://github.com/kaidotdev/kube-trivy-exporter/releases/tag/v1.0.2

I've fixed it.
https://github.com/kaidotdev/kube-trivy-exporter/commit/4ab595003d9bf00dc819a9730d006d36ec49a209.
